name: CI Checks

on:
  pull_request:
    branches: main

jobs:
  build-db-container:
    name: Build DB container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx for Docker build caching
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile_pgrouting
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/amsterdam/bereikbaarheid-db:latest

  linting-and-tests:
    name: Templates
    needs: build-db-container
    uses: amsterdam/opdrachten-team-github-workflows/.github/workflows/CI.yml@v1
    with:
      repo_name: amsterdam
      project_name: bereikbaarheid